name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 你的默认分支

permissions:
  contents: write  # 必须，用于推送代码到 gh-pages 分支
  pages: write     # 如果你使用的是官方 Pages 部署，则需要这个
  id-token: write  # 同上

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install
      - run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
